import { expect, test } from '@playwright/test';
import { verifyScene } from './scene-check';

test('voyage HUD flows below wrapped missions and compact mobile actions remain accessible', async({page,browser})=>{
  test.setTimeout(180000);
  await page.addInitScript(()=>sessionStorage.setItem('ocean-adventure-graphics','performance'));
  await page.goto('/?qa=reef');
  await page.locator('[data-loading]').waitFor({state:'hidden',timeout:60000});
  const mission=page.locator('.hud__mission'), weather=page.locator('.sea-state');
  const assertWeatherFlow=async()=>{
    const m=await mission.boundingBox(),w=await weather.boundingBox();
    expect(w!.y).toBeGreaterThanOrEqual(m!.y+m!.height+4);
  };
  await assertWeatherFlow();
  await page.screenshot({path:'output/gameplay-round3/09-hud-desktop.png'});
  await page.setViewportSize({width:390,height:844});
  await verifyScene(page);
  await expect(weather).toBeHidden();
  const more=page.getByRole('button',{name:'More voyage actions',exact:true});
  await expect(page.locator('[data-save]')).toBeHidden();
  await more.click();
  await expect(more).toHaveAttribute('aria-expanded','true');
  await expect(page.locator('[data-save]')).toBeVisible();
  const menu=await page.locator('[data-action-menu]').boundingBox();
  expect(menu!.x+menu!.width).toBeLessThanOrEqual(390);
  expect(menu!.y).toBeGreaterThan(0);
  await page.locator('[data-save]').click();
  await expect(more).toBeFocused();
  await expect(more).toHaveAttribute('aria-expanded','false');
  await more.click();
  await page.keyboard.press('Escape');
  await expect(more).toHaveAttribute('aria-expanded','false');
  await expect(page.locator('[data-pause-menu]')).not.toHaveClass(/is-open/);
  const guide=await page.locator('.navigation-guide').boundingBox(),dock=await page.locator('.action-dock').boundingBox();
  expect(guide!.y+guide!.height).toBeLessThanOrEqual(dock!.y-8);
  await page.screenshot({path:'output/gameplay-round3/10-hud-mobile.png'});
  await expect(page.locator('[data-mode-toggle]')).toBeVisible();
  await expect(page.locator('[data-cruise]')).toBeVisible();
  await page.setViewportSize({width:844,height:390});
  await verifyScene(page);
  await assertWeatherFlow();
  const landscapeMission=await mission.boundingBox(),landscapeTools=await page.locator('.dive-tools').boundingBox();
  expect(landscapeMission!.y+landscapeMission!.height).toBeLessThanOrEqual(landscapeTools!.y-8);
  const landscapeDock=await page.locator('.action-dock').boundingBox(),landscapeGuide=await page.locator('.navigation-guide').boundingBox();
  expect(landscapeGuide!.y+landscapeGuide!.height).toBeLessThanOrEqual(landscapeDock!.y-8);
  expect(landscapeDock!.height).toBeLessThanOrEqual(44);
  await expect(page.locator('[data-save]')).toBeHidden();
  await more.click();
  await expect(page.locator('[data-save]')).toBeVisible();
  await page.locator('[data-save]').click();
  await expect(more).toBeFocused();
  await expect(more).toHaveAttribute('aria-expanded','false');
  await page.screenshot({path:'output/gameplay-round3/11-hud-landscape.png'});
  expect(await page.locator('body').evaluate(body=>body.scrollWidth<=innerWidth)).toBe(true);
  await page.close();
  const touch=await browser.newContext({viewport:{width:1280,height:720},hasTouch:true});
  try {
    const screen=await touch.newPage();
    await screen.addInitScript(()=>sessionStorage.setItem('ocean-adventure-graphics','performance'));
    await screen.goto('http://127.0.0.1:5174/?qa=reef');
    await screen.locator('[data-loading]').waitFor({state:'hidden',timeout:60000});
    await verifyScene(screen);
    const actions=await screen.locator('.action-dock').boundingBox(),navigation=await screen.locator('.navigation-guide').boundingBox();
    const tools=await screen.locator('.dive-tools').boundingBox(),movement=await screen.locator('.touch-controls').boundingBox();
    expect(navigation!.y+navigation!.height).toBeLessThanOrEqual(actions!.y-8);
    expect(tools!.x+tools!.width).toBeLessThanOrEqual(movement!.x-8);
    expect(actions!.x+actions!.width).toBeLessThanOrEqual(movement!.x-8);
    await screen.screenshot({path:'output/gameplay-round3/15-hud-touch-desktop.png'});
    await screen.setViewportSize({width:900,height:720});
    const narrowActions=await screen.locator('.action-dock').boundingBox(),narrowGuide=await screen.locator('.navigation-guide').boundingBox();
    expect(narrowGuide!.y+narrowGuide!.height).toBeLessThanOrEqual(narrowActions!.y-8);
    await screen.screenshot({path:'output/gameplay-round3/16-hud-touch-tablet.png'});
  }finally{await touch.close();}
});
