import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import {build} from 'esbuild';
const bundle=await build({stdin:{contents:"export * from './src/salvage.ts';export * from './src/salvage-world.ts';export * from './src/progression.ts';export * from './src/voyage-state.ts';export * from './src/voyage-catalog.ts';export * from './src/field-equipment.ts';export * from './src/research-rov.ts';export {Scene,Vector3,Quaternion,Texture} from 'three';export {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';export {default as RAPIER} from '@dimforge/rapier3d-compat';",resolveDir:fileURLToPath(new URL('../../',import.meta.url)),loader:'ts'},bundle:true,platform:'node',format:'esm',write:false});
const a=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const bayPose={x:a.FIELD_POSTS[0].x,y:0,z:a.FIELD_POSTS[0].z},servicePose={...bayPose,y:-17.2,z:bayPose.z+3},lagoonPose={x:a.FIELD_POSTS[1].x,y:0,z:a.FIELD_POSTS[1].z};
function earned(){const p=a.defaultProgress();p.credits=1000;p.voyage=a.recordContractCompletion(p.voyage,a.contractById('bay-signal'));return p;}
function collect(p,id){const c=a.SALVAGE_CACHES.find(c=>c.id===id);return a.recoverSalvage(p,id,{x:c.x,y:-18,z:c.z},-20,0);}
function supplies(){let p=earned();for(const k of ['alloy','copper','cell'])p=collect(p,`salvage-bay-${k}`);return p;}
function storage(){const values=new Map();a.setProgressStorage({getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)});return values;}
test('fifteen distinct authored cache locations are gated and cannot be recovered from the surface or twice',()=>{
  assert.equal(a.SALVAGE_CACHES.length,15);assert.equal(new Set(a.SALVAGE_CACHES.map(c=>c.id)).size,15);const fresh=a.defaultProgress();assert.throws(()=>collect(fresh,'salvage-bay-alloy'));const p=earned(),c=a.SALVAGE_CACHES[0];assert(!a.salvageReady(p,c.id,{x:c.x,y:0,z:c.z},-20,0));assert(!a.salvageReady(p,c.id,{x:c.x,y:-18,z:c.z},-20,.21));const next=collect(p,c.id);assert.equal(next.salvage.stock.alloy,4);assert.equal(p.salvage,undefined);assert.throws(()=>collect(next,c.id));assert.equal(next.saveVersion,4);assert.equal(next.credits,1000);
});
test('crafting consumes exact earned materials and credits without touching the source or granting mission cargo',()=>{
  const p=supplies(),before=structuredClone(p),next=a.fabricateMaterials(p,'pod');assert.deepEqual(p,before);assert.equal(next.credits,750);assert.deepEqual(next.salvage.stock,{alloy:1,copper:1,cell:1});assert.deepEqual(next.salvage.pod,{built:true,site:null,air:400,energy:300});assert.equal(next.expedition.sold,false);assert.throws(()=>a.fabricateMaterials(next,'pod'));assert.throws(()=>a.fabricateMaterials({...p,credits:249},'pod'));assert.throws(()=>a.fabricateMaterials(earned(),'pod'));
});
test('stock is reconciled against unique recovery receipts and known recipes',()=>{
  const p=supplies();for(const changed of [{...p.salvage,stock:{...p.salvage.stock,alloy:99}},{...p.salvage,recovered:[...p.salvage.recovered,p.salvage.recovered[0]]},{...p.salvage,capacitor:true},{...p.salvage,pod:{...p.salvage.pod,site:'missing'}}])assert.throws(()=>a.sanitizeSalvage(changed));assert.deepEqual(a.sanitizeSalvage(undefined),a.newSalvage());
});
test('capacitor retrofit requires the earned lagoon and owned Manta; it reduces actual drain and accelerates recharge',()=>{
  let p=supplies();assert.throws(()=>a.fabricateMaterials(p,'capacitor'));p.voyage=a.recordContractCompletion(p.voyage,a.contractById('lagoon-echo'));p.fieldEquipment={scooter:true,charge:50};p=collect(p,'salvage-lagoon-alloy');p=a.fabricateMaterials(p,'pod');const next=a.fabricateMaterials(p,'capacitor');assert(next.salvage.capacitor);assert.equal(next.credits,500);assert.throws(()=>a.fabricateMaterials(next,'capacitor'));
  const state={aboard:false,enabled:true,forward:1,boost:false,depth:10,assisting:false};assert(a.scooterStep(next.fieldEquipment,.1,{...state,retrofit:true}).charge>a.scooterStep(next.fieldEquipment,.1,state).charge);assert(a.scooterStep(next.fieldEquipment,.1,{...state,aboard:true,retrofit:true}).charge>a.scooterStep(next.fieldEquipment,.1,{...state,aboard:true}).charge);
});
test('pod placement requires stopped surface helm at a designated unlocked socket; pack and redeploy preserve depletion',()=>{
  let p=a.fabricateMaterials(supplies(),'pod');assert.throws(()=>a.deployPod(p,'bay',{x:0,y:0,z:20},0));assert.throws(()=>a.deployPod(p,'bay',{...bayPose,y:-15},0));assert.throws(()=>a.deployPod(p,'bay',bayPose,1));p=a.deployPod(p,'bay',bayPose,0);assert.throws(()=>a.deployPod(p,'lagoon',lagoonPose,0));
  p.fieldEquipment={scooter:true,charge:40};const serviced=a.servicePod(p,servicePose,-20,0,'swim',50);assert.equal(serviced.oxygen,100);assert.equal(serviced.progress.fieldEquipment.charge,100);assert.equal(serviced.progress.salvage.pod.air,350);assert.equal(serviced.progress.salvage.pod.energy,240);
  p=a.packPod(serviced.progress,bayPose,0);assert.equal(p.salvage.pod.site,null);p=a.deployPod(p,'lagoon',lagoonPose,0);assert.equal(p.salvage.pod.air,350);assert.equal(p.salvage.pod.energy,240);assert.throws(()=>a.packPod(p,bayPose,0));
});
test('ROV power service uses finite energy without awarding diver air, credits or records',()=>{
  const p=a.deployPod(a.fabricateMaterials(supplies(),'pod'),'bay',bayPose,0);p.rov={version:1,owned:true,battery:20};const next=a.servicePod(p,servicePose,-20,0,'rov',37);assert.equal(next.oxygen,37);assert.equal(next.progress.rov.battery,100);assert.equal(next.progress.salvage.pod.energy,220);assert.equal(next.progress.salvage.pod.air,400);assert.equal(next.progress.credits,p.credits);assert.deepEqual(next.progress.expedition,p.expedition);assert.equal(p.rov.battery,20);assert.throws(()=>a.servicePod(p,bayPose,-20,0,'rov',37));assert.throws(()=>a.servicePod(p,servicePose,-20,0,'walk',37));
});
test('resupply is paid and only possible for a packed depleted pod',()=>{
  let p=a.deployPod(a.fabricateMaterials(supplies(),'pod'),'bay',bayPose,0);p=a.servicePod(p,servicePose,-20,0,'swim',50).progress;assert.throws(()=>a.fabricateMaterials(p,'refill'));p=a.packPod(p,bayPose,0);const before=p.credits,next=a.fabricateMaterials(p,'refill');assert.equal(next.credits,before-125);assert.equal(next.salvage.pod.air,400);assert.throws(()=>a.fabricateMaterials(next,'refill'));assert.deepEqual(next.salvage.stock,p.salvage.stock);
});
test('rear pod approaches ascend over the cabinet, then descend outside its front before service',()=>{
  const p=a.deployPod(a.fabricateMaterials(supplies(),'pod'),'bay',bayPose,0),rear={x:bayPose.x+4.5,y:-17.2,z:bayPose.z-3};let g=a.podApproach(p,rear,-20);assert(g.via);assert.equal(g.x,rear.x);assert.equal(g.z,rear.z);assert.equal(g.y,-15.4);
  g=a.podApproach(p,{...rear,y:-15.4},-20);assert(g.via);assert.equal(g.z,bayPose.z+4.5);assert.equal(g.y,-15.4);
  g=a.podApproach(p,{x:bayPose.x,y:-15.4,z:bayPose.z+4.5},-20);assert(g.via);assert.equal(g.y,-17.2);
  g=a.podApproach(p,{x:bayPose.x,y:-17.2,z:bayPose.z+4.5},-20);assert(!g.via);assert.equal(g.z,servicePose.z);
});
test('version four protects salvage; legacy and paid ROV versions retain their bank and equipment',()=>{
  const p=supplies(),values=storage();a.saveProgress(p);const loaded=a.loadProgress();assert.equal(loaded.saveVersion,4);assert.deepEqual(loaded.salvage,p.salvage);assert.deepEqual(a.readProgressImport(a.exportProgress(p)).salvage,p.salvage);assert.equal(a.normalizeProgress(earned()).saveVersion,2);
  const missing=structuredClone(loaded);delete missing.salvage;values.set('ocean-adventure-progress-v1',JSON.stringify(missing));assert.deepEqual(a.loadProgress().salvage,p.salvage);assert.equal(a.progressLoadStatus,'recovered');
  const funded=structuredClone(p);funded.voyage.completed.push('reach-archive');funded.voyage.blueprints.push('research-rov');assert.equal(a.fabricateRov(funded).saveVersion,4);
});
test('all future nested schemas preflight before a recoverable missing salvage record',()=>{
  for(const key of ['story','voyage','expedition','rov','salvage']){const p=supplies(),values=storage();a.saveProgress(p);const damaged=structuredClone(p);delete damaged.salvage;if(key==='salvage')damaged.salvage={version:2};else damaged[key]={...damaged[key],version:key==='expedition'?4:2};const raw=JSON.stringify(damaged);values.set('ocean-adventure-progress-v1',raw);assert.throws(()=>a.loadProgress(),a.ProgressLoadError);assert.equal(values.get('ocean-adventure-progress-v1'),raw);}
});
test('explicit future recovery and mooring identifiers block backup rollback even with incomplete current equipment',()=>{
  for(const kind of ['cache','site']){const p=supplies(),values=storage();a.saveProgress(p);const changed=structuredClone(p);delete changed.rov;if(kind==='cache')changed.salvage.recovered.push('salvage-unreleased-alloy');else changed.salvage.pod.site='unreleased';const raw=JSON.stringify(changed);values.set('ocean-adventure-progress-v1',raw);assert.throws(()=>a.loadProgress(),a.ProgressLoadError);assert.equal(values.get('ocean-adventure-progress-v1'),raw);}
});
test('a saved outpost cannot bypass the required regional receipt',()=>{const p=a.fabricateMaterials(supplies(),'pod');p.salvage.pod.site='reach';assert.throws(()=>a.normalizeProgress(p),/unlocked mooring/);});
test('failed recovery, fabrication and service writes preserve the prior stored receipt and live state',()=>{
  for(const kind of ['recovery','craft','service']){let p=kind==='recovery'?earned():supplies();if(kind==='service')p=a.deployPod(a.fabricateMaterials(p,'pod'),'bay',bayPose,0);const values=storage();a.saveProgress(p);const old=values.get('ocean-adventure-progress-v1'),before=structuredClone(p);a.setProgressStorage({getItem:k=>values.get(k)??null,setItem:()=>{throw Error('quota');}});a.loadProgress();const next=kind==='recovery'?collect(p,'salvage-bay-alloy'):kind==='craft'?a.fabricateMaterials(p,'pod'):a.servicePod(p,servicePose,-20,0,'swim',50).progress;assert.throws(()=>a.saveProgress(next));assert.equal(values.get('ocean-adventure-progress-v1'),old);assert.deepEqual(p,before);}
});
test('authored five-component kit uses shared geometry and actual native body collision',async()=>{
  await a.RAPIER.init();const bytes=await readFile(new URL('../../public/models/calypso_field_kit.glb',import.meta.url));assert(bytes.length<700000);const asset=await new a.GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),''),world=new a.SalvageWorld(new a.Scene(),()=>-20,new a.Texture());world.attach(asset.scene);const p=a.deployPod(a.fabricateMaterials(supplies(),'pod'),'bay',bayPose,0);world.update(p,new a.Vector3(bayPose.x,-17,servicePose.z),0,()=>0);
  try{assert(world.loaded);let paints=0;world.root.traverse(n=>{if(n.material?.name==='Calypso enamel'){paints++;assert(n.geometry.attributes.uv);}});assert(paints>5);const pos=new a.Vector3(bayPose.x,-18.5,bayPose.z-3);world.resolve(pos,new a.Vector3(bayPose.x,-18.5,bayPose.z+4));assert(Math.abs(pos.z-(bayPose.z+.83+1.12+.015))<.01,`Full ROV radius did not stop at the pod front ${JSON.stringify(pos)}`);const diver=new a.Vector3(bayPose.x,-17.2,servicePose.z);world.resolve(diver,new a.Vector3(bayPose.x,-17.2,bayPose.z+6),new a.Quaternion());assert(diver.z<bayPose.z+3.5,'Service connectors are inaccessible');
    const route=[[bayPose.x+4.5,-17.2,bayPose.z-3],[bayPose.x+4.5,-15.4,bayPose.z-3],[bayPose.x,-15.4,bayPose.z+4.5],[bayPose.x,-17.2,bayPose.z+4.5],[bayPose.x,-17.2,servicePose.z]];for(let i=1;i<route.length;i++){const goal=new a.Vector3(...route[i]);world.resolve(goal,new a.Vector3(...route[i-1]));assert(goal.distanceTo(new a.Vector3(...route[i]))<.02,`Blocked staged pod approach ${i}`);}
    const contacts=world.contacts(p,new a.Vector3(bayPose.x,-17,bayPose.z));assert(contacts.some(c=>c.id==='calypso-service'));assert(!contacts.some(c=>c.id==='salvage-bay-alloy'));}finally{world.dispose();}
});
